services:
  bill-record:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_BASE_URL: /api
    image: bill-record:latest
    container_name: bill-record
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      NITRO_HOST: 0.0.0.0
    # 当前无状态，不需要数据卷
    # volumes:
    #   - ./logs:/app/logs
